apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "master"
jobs:
  build:
    steps:
      - name: Add labels
        uses: cloudbees-io/label-artifact-version@main
        with:
          component-id: "daf6328c-a799-4d3a-92c7-c32c1c6e07eb"
          artifact-id: "ee5b22f9-18ac-456c-a754-fede35272ec0"
          labels: "ready"
          operation: "ADD"