name: Build and Push Go Service

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true  # Caches dependencies

      - name: Build Go Application
        run: |
          go mod tidy
          go install .  

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Docker Image Tag
        id: set-tag
        run: echo "image_tag=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Image 
        env:
          DOCKER_BUILDKIT: 1  # Enables BuildKit for speed
        run: |
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/demo-service"
          IMAGE_TAG="${{ steps.set-tag.outputs.image_tag }}"

          docker build -t $IMAGE_NAME:$IMAGE_TAG --progress=plain .
          docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$IMAGE_TAG
          docker push $IMAGE_NAME:latest

      - name: Get Image Digest
        id: image-digest
        run: |
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/demo-service"
          DIGEST=$(docker manifest inspect $IMAGE_NAME:${{ steps.set-tag.outputs.image_tag }} | jq -r '.manifests[0].digest')
          echo "digest=$DIGEST" >> $GITHUB_OUTPUT

      - name: Register Artifact with CloudBees
        uses: cloudbees-gha-cbp/register-build-artifact@main
        with:
          name: "demo-service"
          version: "${{ steps.set-tag.outputs.image_tag }}"
          url: "docker.io/${{ secrets.DOCKER_USERNAME }}/demo-service:${{ steps.set-tag.outputs.image_tag }}"
          digest: "${{ steps.image-digest.outputs.digest }}"
          type: "docker"
          cloudbees-url: "https://api.saas-preprod.beescloud.com"
          cloudbees-pat: ${{ secrets.CBP_PAT }}
